### ISSUE TITLE
Very useful, thank you very much.

### ISSUE THREAD

**Issue by EkkoGithub2021** [anuragkanwar/modern-react-snippets-plugin#1]
It's exactly what I need.

**Comment by anuragkanwar** [comment]
Thanks @EkkoGithub2021, instead giving reviews here it might be helpful to give reviews on jetbrains official plugins page 😅

**Comment by anuragkanwar** [comment]
Thanks @EkkoGithub2021, instead giving reviews here it might be helpful to give reviews on jetbrains official plugins page 😅
