### ISSUE TITLE
Snippets not automatically available in .ts and .tsx files

### ISSUE THREAD

**Issue by javiev** [anuragkanwar/modern-react-snippets-plugin#4]
Following a clean installation of WebStorm version 2023.3.4 and the latest plugin version 1.0.2, I've encountered an issue where code snippets are not automatically available or functioning in .ts and .tsx files. Despite attempting to use snippets in these TypeScript files, they fail to appear in the autocomplete suggestion list.

To access the desired snippets, it's currently necessary to navigate to **Editor > Live Templates** and manually activate each snippet for use in TypeScript files.

<img width="1518" alt="imagen" src="https://github.com/anuragkanwar/modern-react-snippets-plugin/assets/7276016/d92861ca-8fa2-454d-b00c-1b25513c6f44">

**Comment by javiev** [comment]
Hi @anuragkanwar, any chance of fixing the bug related to the .ts and .tsx extensions soon? The plugin became incompatible with the latest version of WebStorm

<img width="323" alt="imagen" src="https://github.com/anuragkanwar/modern-react-snippets-plugin/assets/7276016/20992ed6-da4a-4af8-b8ee-1991136984f2">

**Comment by anuragkanwar** [comment]
update OTW

**Comment by javiev** [comment]
great, tyty
